import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Second from '../../components/Second'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>E-commerce site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=''>
      <div className="" >
        {/* <img
          className=" my-1 w-screen"
          src="/images/bg.png"
          alt="Picture of the author"
        /> */}
        <Second/>
      </div>


      </div>
    </>
  );
}
